### ISSUE TITLE
The new version doesn't function with Anki 2.1.54. How can I revert to the previous version?

### ISSUE THREAD

**Issue by EugeneTarasenko** [Ambriel/advanced_copy_fields#4]
The latest version of Advanced Copy Fields is not compatible with Anki 2.1.54

<img width="333" alt="Screen Shot 2023-12-23 at 21 10 27" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/f6f598b1-1e42-4a2f-b149-35a2ebc3c379">

And it throws an error with the new Anki 23.10.1. You can find more details here: https://github.com/Ambriel/advanced_copy_fields/issues/3

How can I roll back to the previous version of Advanced Copy Fields? It was working perfectly before, but now it is not functioning."

<img width="713" alt="Screen Shot 2023-12-23 at 21 07 38" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/4a4e9c23-4eb3-4e5e-801e-8b02777c9c91">

**Comment by Ambriel** [comment]
I've now created releases to keep up with versions. That referenced version, which is the prior version [2019-05-03](https://github.com/Ambriel/advanced_copy_fields/releases/tag/v0.3.0) can be downloaded from [releases](https://github.com/Ambriel/advanced_copy_fields/releases).

I've been caught away in other activities for a while, however, there should be a way to program dual support for QT5 and QT6 from the same release. In the future, I hope I or someone else working on this or other ACF forks can implement that to make it seamless for the end user. I hope this suffice, in the meantime.
